### ISSUE TITLE
error while save users

### ISSUE THREAD

**Issue by mangopik** [mangopik/sximo5#10]
cant save or apply users info on users module

**Comment by mangopik** [comment]
**Step 1**

open file /resources/views/core/users/form.blade.php . edit line 31 
```
 {!! Form::open(array('url'=>'core/users/save?return='.$return, 'class'=>'form-horizontal','files' => true , 'parsley-validate'=>'','novalidate'=>' ')) !!}
```

**Step 2**
Open file /app/Http/Controllers/Core/UsersController.php . Edit line 170

```
$id = $this->model->insertRow($data , $request->input('id'));
```

**Comment by DiegoGiovany** [comment]
where to download updated version? I have the purchase code...

**Comment by mangopik** [comment]
Sximobuilder.com/download
