### ISSUE TITLE
can't add new user (admin, user ) ( sxismo 5.1 and ajax plugin ) 

### ISSUE THREAD

**Issue by HammGsm** [mangopik/sximo5#14]
http://localhost/core/users/save?return=
![captura de pantalla 2015-07-09 a las 16 20 37](https://cloud.githubusercontent.com/assets/5256682/8607154/8e2ff23c-2656-11e5-85c8-74f4965f24d2.png)
![captura de pantalla 2015-07-09 a las 16 20 19](https://cloud.githubusercontent.com/assets/5256682/8607155/8ec27aee-2656-11e5-9f17-4e595f9018d9.png)

**Comment by mangopik** [comment]
this issue same as this https://github.com/mangopik/sximo5/issues/10
