### ISSUE TITLE
How to show master-detail menu?

### ISSUE THREAD

**Issue by shootsoft** [mangopik/sximo5#15]
In 3.x version, it can be shown automatically. Is it a bug in this version?

**Comment by mangopik** [comment]
it will not show menu , master detail only appear once you click view detail or form

**Comment by shootsoft** [comment]
This version does not support multiple details page now?

Like this:
- TableA -> Master
- TableB -> Detail Part 1
- TableC -> Detail Part 2

**Comment by mangopik** [comment]
Not yet for this moment
