### ISSUE TITLE
sximo5 with ajax - can't enable ajax

### ISSUE THREAD

**Issue by Jagy2014** [mangopik/sximo5#18]
I can’t enable them ajax. When I change module settings to ajax and press save button, check box switch back to native.

**Comment by mangopik** [comment]
you need to add more option ('ajax')  in your module_type ( enum ) field on tb_module tables .

**Comment by Jagy2014** [comment]
I used sximo3 before and not read documentation for sximo5. Now I read it. Thanks.

Ajax enabled. Now I rebuild module and get: http://i.imgur.com/okCIgdL.png
