### ISSUE TITLE
Captcha register issue

### ISSUE THREAD

**Issue by mangopik** [mangopik/sximo5#2]
Error registration page if captcha enable

**Comment by aketai** [comment]
recaptcha image not appear

**Comment by mangopik** [comment]
Do you have error notification ?

**Comment by aketai** [comment]
No error notification, 
please see attached snapshot:
![snapshot](https://cloud.githubusercontent.com/assets/13001680/8447948/44b42ac6-1fe2-11e5-947b-5559141b5101.jpg)
captcha image not appear.

**Comment by mangopik** [comment]
If you on windows os , please make sure  GD2 DLL php_gd2.dll is enable

**Comment by SrPatinhas** [comment]
@mangopik maybe another solution for captcha? like the im not a robot or something like that?
