### ISSUE TITLE
Contoller Report issue

### ISSUE THREAD

**Issue by mangopik** [mangopik/sximo5#5]
issue while loading model on controller report

**Comment by mangopik** [comment]
Solution

Edit file /resources/views/sximo/module/template/report/controller.tpl

change line 4 to be

```
use App\Models\{controller};
```

**Comment by notridan** [comment]
report.tpl does not exist. I believe that this change must be made in controller.tpl, correct?

**Comment by mangopik** [comment]
yes you're right . its controller.tpl file .
